// Dicionário central de strings de interface (PT/EN).
// Não confundir com conteúdo de questões/flashcards/glossário — esses já são
// bilíngues via locales.pt/locales.en nos próprios dados.
export const UI = {
  pt: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossário", progress: "Progresso" },
    footer: "Material de estudo independente, não afiliado ao ISTQB.",
    questionsCount: "questões",
    domainAll: "Todos",
    domainAllDesc: "Mistura de todos os capítulos",
    quiz: {
      modeStudy: "Estudo", modeStudyDesc: "Feedback e explicação a cada questão",
      modeExam: "Simulado",
      modeExamDesc: "{n} questões · {min} min · revisão no fim",
      modeSaved: "★ Salvos",
      modeSavedDesc: "{n} questão(ões) marcada(s) para revisar",
      chooseDomain: "Escolha o domínio",
      allDomains: "Todos os domínios",
      wrongBefore: "Errei antes",
      wrongBeforeDesc: "{n} questão(ões) que você errou",
      quantity: "Quantidade:", all: "Todas",
      start: "Iniciar",
      savedReviewHint: "Revise as {n} questão(ões) que você marcou com ★ durante o estudo.",
      examExplain: "O modo Simulado reproduz a prova: {n} questões na proporção dos capítulos, cronômetro de {min} minutos (tempo estendido para não-nativos), sem feedback até o final.",
      passed: "Aprovado", failed: "Abaixo da nota de corte",
      excellentMsg: "Excelente domínio. Pronto para a prova.",
      passedMsg: "Passou! Reforce os domínios mais fracos na aba Progresso.",
      failedMsg: "A nota de corte é 65% (26/40). Revise os erros abaixo.",
      backHome: "← Voltar ao início", backShort: "← Voltar",
      hideReview: "Ocultar revisão", showReview: "Revisar erros",
      retakeQuiz: "Refazer este quiz",
      reviewErrors: "Revisão dos erros", noErrors: "Nenhum erro — gabaritou!",
      yourAnswer: "Sua resposta:", notAnswered: "não respondida", correctAnswer: "Correta:",
      questionOf: "Questão {n} de {total}",
      saved: "★ Salvo", saveQuestion: "☆ Salvar questão",
      prev: "← Anterior", next: "Próxima →",
      finishExam: "Finalizar simulado", seeResult: "Ver resultado",
      terms: "Termos: ",
      modeSRS: "Revisão", srsDueDesc: "questão(ões) para revisar hoje",
      srsAgain: "Errei", srsHard: "Difícil", srsGood: "Bom", srsEasy: "Fácil",
      showGrid: "Ver todas as questões", hideGrid: "Ocultar grade",
      gridSummary: "{answered} de {total} respondidas · {blank} em branco",
    },
    stats: {
      importSuccess: "Progresso importado com sucesso.",
      importError: "Arquivo inválido. Use um arquivo exportado por este app.",
      answered: "Respondidas", correct: "Acertos", performance: "Aproveitamento",
      evolution: "Evolução",
      noHistory: "Sem histórico ainda. Responda algumas questões para ver sua evolução aqui.",
      byDomain: "Por domínio", noData: "sem dados",
      coverage: "Cobertura por capítulo",
      coverageDesc: "Questões vistas ao menos uma vez (modos Estudo e Errei antes)",
      metaTitle: "Meta CTFL v4.0:",
      metaText: "40 questões, mínimo 26 acertos (65%). Os capítulos 4 (Técnicas) e 5 (Gerenciamento) somam metade do exame — priorize-os. Há cerca de 8 questões K3 (aplicação), as mais difíceis.",
      exportBtn: "Exportar progresso", importBtn: "Importar progresso",
      resetBtn: "Zerar", resetConfirm: "Zerar todo o progresso?",
      precisionLabel: "PRECISÃO", coverageLabel: "ALCANCE",
    },
    flashcards: {
      flip: "toque para revelar", prev: "← Anterior", next: "Próximo →",
      again: "Errei", hard: "Difícil", good: "Bom", easy: "Fácil",
      dueToday: "Para revisar hoje",
    },
    syllabus: { ofQuestions: "de {total} questões neste banco", studyChapter: "Estudar este capítulo →" },
    onboarding: {
      examCardDesc: "40 questões em 75 minutos, igual à prova real. Revisão de erros no fim.",
      statsQuestions: "200 questões",
      badge: "Baseado no syllabus oficial ISTQB CTFL v4.0",
      heroValueProp: "Tudo que você precisa para passar no CTFL, de graça.",
      heroSubtitle: "Preparação gratuita para o exame ISTQB Foundation Level v4.0",
      statDomains: "6 domínios",
      statLang: "PT/EN",
      statFree: "Gratuito",
      ctaStart: "Começar →",
      ctaStartFinal: "Começar a estudar →",

      featuresTitle: "O que você vai encontrar",
      featureStudyTitle: "Quiz — modo Estudo",
      featureStudyDesc: "Feedback e explicação a cada questão. Filtre por domínio ou revise o que errou.",
      featureExamTitle: "Simulado cronometrado",
      featureSRSTitle: "Revisão espaçada (SM-2)",
      featureSRSDesc: "Modo Revisão no Quiz e Flashcards com Errei/Difícil/Bom/Fácil — repita só o que precisa.",
      featureGlossaryTitle: "Glossário oficial ISTQB",
      featureGlossaryDesc: "70 termos em PT/EN, integrados automaticamente nas explicações das questões.",
      featureProgressTitle: "Progresso detalhado",
      featureProgressDesc: "Cobertura por capítulo, evolução diária, exportar/importar dados.",
      featureBilingualTitle: "100% bilíngue",
      featureBilingualDesc: "Alterne PT/EN a qualquer momento — ideal para quem presta a prova em inglês.",

      mockupTitle: "Veja como funciona",
      mockupDomain: "Fundamentos",
      mockupQuestion: "Qual é a relação correta entre erro, defeito e falha?",
      mockupOptA: "São sinônimos",
      mockupOptB: "Erro gera defeito, que gera falha",
      mockupOptC: "Falha gera erro",

      socialFreeText: "100% gratuito, sem cadastro, sem anúncios",
      socialOpenSourceText: "Código aberto no GitHub",
      socialFutureNote: "Em construção: mais certificações ISTQB em breve.",

      faqTitle: "Perguntas frequentes",
      faqQ1: "Preciso me cadastrar?",
      faqA1: "Não, nunca. Tudo funciona sem login.",
      faqQ2: "É realmente gratuito?",
      faqA2: "Sim, sem anúncios, sem plano pago, sem pegadinha.",
      faqQ3: "O conteúdo é oficial do ISTQB?",
      faqA3: "Baseado no syllabus público CTFL v4.0, mas o app não é afiliado ao ISTQB.",
      faqQ4: "Funciona no celular?",
      faqA4: "Sim, é instalável como app (PWA), funciona offline.",
      faqQ5: "Posso usar em inglês?",
      faqA5: "Sim, alterne PT/EN a qualquer momento no topo do app.",

      authorTitle: "Sobre o autor",
      authorBio: "Feito por Ironides Francisco — QA Analyst, construído como projeto pessoal de estudo e portfólio.",
    },
    notifications: {
      title: "Lembretes",
      enable: "Ativar notificações",
      enabled: "Notificações ativadas.",
      blocked: "Notificações bloqueadas no navegador. Ative nas configurações do site.",
    },
  },
  en: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossary", progress: "Progress" },
    footer: "Independent study material, not affiliated with ISTQB.",
    questionsCount: "questions",
    domainAll: "All",
    domainAllDesc: "Mix of all chapters",
    quiz: {
      modeStudy: "Study", modeStudyDesc: "Feedback and explanation for each question",
      modeExam: "Exam Simulation",
      modeExamDesc: "{n} questions · {min} min · review at the end",
      modeSaved: "★ Saved",
      modeSavedDesc: "{n} question(s) marked for review",
      chooseDomain: "Choose the domain",
      allDomains: "All domains",
      wrongBefore: "Mistakes before",
      wrongBeforeDesc: "{n} question(s) you got wrong",
      quantity: "Quantity:", all: "All",
      start: "Start",
      savedReviewHint: "Review the {n} question(s) you marked with ★ during study.",
      examExplain: "Exam Simulation mode replicates the real exam: {n} questions in chapter proportion, {min}-minute timer (extended time for non-native speakers), no feedback until the end.",
      passed: "Passed", failed: "Below the passing score",
      excellentMsg: "Excellent mastery. Ready for the exam.",
      passedMsg: "Passed! Reinforce your weaker domains in the Progress tab.",
      failedMsg: "The passing score is 65% (26/40). Review the mistakes below.",
      backHome: "← Back to start", backShort: "← Back",
      hideReview: "Hide review", showReview: "Review mistakes",
      retakeQuiz: "Retake this quiz",
      reviewErrors: "Mistake review", noErrors: "No mistakes — perfect score!",
      yourAnswer: "Your answer:", notAnswered: "not answered", correctAnswer: "Correct:",
      questionOf: "Question {n} of {total}",
      saved: "★ Saved", saveQuestion: "☆ Save question",
      prev: "← Previous", next: "Next →",
      finishExam: "Finish exam", seeResult: "See result",
      terms: "Terms: ",
      modeSRS: "Review", srsDueDesc: "question(s) due today",
      srsAgain: "Again", srsHard: "Hard", srsGood: "Good", srsEasy: "Easy",
      showGrid: "View all questions", hideGrid: "Hide grid",
      gridSummary: "{answered} of {total} answered · {blank} blank",
    },
    stats: {
      importSuccess: "Progress imported successfully.",
      importError: "Invalid file. Use a file exported by this app.",
      answered: "Answered", correct: "Correct", performance: "Performance",
      evolution: "Evolution",
      noHistory: "No history yet. Answer some questions to see your evolution here.",
      byDomain: "By domain", noData: "no data",
      coverage: "Coverage by chapter",
      coverageDesc: "Questions seen at least once (Study and Mistakes Only modes)",
      metaTitle: "CTFL v4.0 goal:",
      metaText: "40 questions, minimum 26 correct (65%). Chapters 4 (Techniques) and 5 (Management) make up half the exam — prioritize them. There are about 8 K3 (application) questions, the hardest ones.",
      exportBtn: "Export progress", importBtn: "Import progress",
      resetBtn: "Reset", resetConfirm: "Reset all progress?",
      precisionLabel: "ACCURACY", coverageLabel: "COVERAGE",
    },
    flashcards: {
      flip: "tap to reveal", prev: "← Previous", next: "Next →",
      again: "Again", hard: "Hard", good: "Good", easy: "Easy",
      dueToday: "Due today",
    },
    syllabus: { ofQuestions: "of {total} questions in this bank", studyChapter: "Study this chapter →" },
    onboarding: {
      examCardDesc: "40 questions in 75 minutes, just like the real exam. Mistake review at the end.",
      statsQuestions: "200 questions",
      badge: "Based on the official ISTQB CTFL v4.0 syllabus",
      heroValueProp: "Everything you need to pass CTFL, for free.",
      heroSubtitle: "Free prep for the ISTQB Foundation Level v4.0 exam",
      statDomains: "6 domains",
      statLang: "PT/EN",
      statFree: "Free",
      ctaStart: "Start →",
      ctaStartFinal: "Start studying →",

      featuresTitle: "What you'll find",
      featureStudyTitle: "Quiz — Study mode",
      featureStudyDesc: "Feedback and explanation for every question. Filter by domain or review your mistakes.",
      featureExamTitle: "Timed exam simulation",
      featureSRSTitle: "Spaced repetition (SM-2)",
      featureSRSDesc: "Review mode in Quiz and Flashcards rating Again/Hard/Good/Easy — repeat only what you need.",
      featureGlossaryTitle: "Official ISTQB glossary",
      featureGlossaryDesc: "70 terms in PT/EN, automatically linked in question explanations.",
      featureProgressTitle: "Detailed progress",
      featureProgressDesc: "Coverage by chapter, daily evolution, export/import data.",
      featureBilingualTitle: "100% bilingual",
      featureBilingualDesc: "Switch PT/EN anytime — ideal if you're taking the exam in English.",

      mockupTitle: "See how it works",
      mockupDomain: "Fundamentals",
      mockupQuestion: "What is the correct relationship between error, defect, and failure?",
      mockupOptA: "They are synonyms",
      mockupOptB: "Error causes a defect, which causes a failure",
      mockupOptC: "Failure causes an error",

      socialFreeText: "100% free, no sign-up, no ads",
      socialOpenSourceText: "Open source on GitHub",
      socialFutureNote: "In progress: more ISTQB certifications coming soon.",

      faqTitle: "Frequently asked questions",
      faqQ1: "Do I need to sign up?",
      faqA1: "No, never. Everything works without login.",
      faqQ2: "Is it really free?",
      faqA2: "Yes, no ads, no paid plan, no catch.",
      faqQ3: "Is the content official ISTQB material?",
      faqA3: "Based on the public CTFL v4.0 syllabus, but the app is not affiliated with ISTQB.",
      faqQ4: "Does it work on mobile?",
      faqA4: "Yes, it's installable as an app (PWA) and works offline.",
      faqQ5: "Can I use it in English?",
      faqA5: "Yes, switch PT/EN anytime at the top of the app.",

      authorTitle: "About the author",
      authorBio: "Built by Ironides Francisco — QA Analyst, made as a personal study and portfolio project.",
    },
    notifications: {
      title: "Reminders",
      enable: "Enable notifications",
      enabled: "Notifications enabled.",
      blocked: "Notifications blocked in browser. Enable it in site settings.",
    },
  },
};

export function t(lang, path, vars = {}) {
  const parts = path.split(".");
  let node = UI[lang] || UI.pt;
  for (const p of parts) node = node?.[p];
  if (typeof node !== "string") return path; // fallback visível p/ debug
  return node.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? "");
}
