// Dicionário central de strings de interface (PT/EN).
// Não confundir com conteúdo de questões/flashcards/glossário — esses já são
// bilíngues via locales.pt/locales.en nos próprios dados.
export const UI = {
  pt: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossário", progress: "Progresso" },
    footer: "Material de estudo independente, não afiliado ao ISTQB.",
    questionsCount: "questões",
    changeCert: "Trocar certificação",
    langToggleToEn: "Mudar idioma para inglês", langToggleToPt: "Mudar idioma para português",
    themeAuto: "Tema: automático", themeLight: "Tema: claro", themeDark: "Tema: escuro",
    domainAll: "Todos",
    domainAllDesc: "Mistura de todos os capítulos",
    quiz: {
      modeStudy: "Estudo", modeStudyDesc: "Feedback e explicação a cada questão",
      modeExam: "Simulado",
      modeExamDesc: "{n} questões · {min} min · revisão no fim",
      modeSaved: "★ Salvos",
      modeSavedDesc: "{n} questão(ões) marcada(s) para revisar",
      chooseDomain: "Escolha o domínio",
      allDomains: "Todos os domínios",
      wrongBefore: "Errei antes",
      wrongBeforeDesc: "{n} questão(ões) que você errou",
      quantity: "Quantidade:", all: "Todas",
      start: "Iniciar",
      savedReviewHint: "Revise as {n} questão(ões) que você marcou com ★ durante o estudo.",
      examExplain: "O modo Simulado reproduz a prova: {n} questões na proporção dos capítulos, cronômetro de {min} minutos (tempo estendido para não-nativos), sem feedback até o final.",
      passed: "Aprovado", failed: "Abaixo da nota de corte",
      excellentMsg: "Excelente domínio. Pronto para a prova.",
      passedMsg: "Passou! Reforce os domínios mais fracos na aba Progresso.",
      failedMsg: "A nota de corte é 65% (26/40). Revise os erros abaixo.",
      backHome: "← Voltar ao início", backShort: "← Voltar",
      hideReview: "Ocultar revisão", showReview: "Revisar erros",
      retakeQuiz: "Refazer este quiz",
      reviewErrors: "Revisão dos erros", noErrors: "Nenhum erro — gabaritou!",
      yourAnswer: "Sua resposta:", notAnswered: "não respondida", correctAnswer: "Correta:",
      questionOf: "Questão {n} de {total}",
      saved: "★ Salvo", saveQuestion: "☆ Salvar questão",
      prev: "← Anterior", next: "Próxima →",
      finishExam: "Finalizar simulado", seeResult: "Ver resultado",
      terms: "Termos: ",
      modeSRS: "Revisão", srsDueDesc: "questão(ões) para revisar hoje",
      srsAgain: "Errei", srsHard: "Difícil", srsGood: "Bom", srsEasy: "Fácil",
      showGrid: "Ver todas as questões", hideGrid: "Ocultar grade",
      gridSummary: "{answered} de {total} respondidas · {blank} em branco",
      weakestChapter: "Capítulo mais fraco: {chapter} ({pct}%). Estude para melhorar.",
      studyChapter: "Estudar {chapter} →",
    },
    stats: {
      importSuccess: "Progresso importado com sucesso.",
      importError: "Arquivo inválido. Use um arquivo exportado por este app.",
      answered: "Respondidas", correct: "Acertos", performance: "Aproveitamento",
      evolution: "Evolução",
      noHistory: "Sem histórico ainda. Responda algumas questões para ver sua evolução aqui.",
      emptyWelcome: "Você ainda não respondeu nenhuma questão.",
      emptyCta: "Ir para o Quiz",
      byDomain: "Por domínio", noData: "sem dados",
      coverage: "Cobertura por capítulo",
      coverageDesc: "Questões vistas ao menos uma vez (modos Estudo, Errei antes e Simulado)",
      metaTitle: "Meta {cert}:",
      metaText: "{examQuestions} questões, mínimo {passMark} acertos ({passPct}%).",
      exportBtn: "Exportar progresso", importBtn: "Importar progresso",
      resetBtn: "Zerar", resetConfirm: "Zerar todo o progresso?",
      precisionLabel: "PRECISÃO", coverageLabel: "ALCANCE",
      readinessPrefix: "Você está em", readinessSuffix: "de prontidão pra {cert}.",
      readinessLowConfidence: "Continue respondendo — faltam pelo menos {n} questões para uma estimativa confiável.",
      pacePrefix: "Nesse ritmo, chega a 90% em ~", paceSuffix: " semanas.",
      level: "Nível", achievementsLabel: "conquistas",
      readinessCI: "Intervalo real: {low}%–{high}%",
      readinessCoverage: "Cobertura: {pct}% do banco ({seen}/{total})",
      readinessPreliminary: "Estimativa preliminar — responda mais questões para um veredito confiável.",
      readinessReady: "✓ Pronto para a prova",
      readinessNotReady: "Ainda não — continue praticando",
      howItWorks: "Como funciona?",
      infoAproveitamento: "% de acerto sobre todas as tentativas (inclui re-respostas). Reflete volume, não retenção.",
      infoProntidao: "% de questões únicas que você acertou por último, com intervalo de confiança. Reflete retenção, não volume.",
      streakDesc: "Dias consecutivos com ≥5 questões respondidas",
      levelDesc: "Nível baseado em questões únicas corretas",
    },
    flashcards: {
      flip: "toque para revelar", prev: "← Anterior", next: "Próximo →",
      again: "Errei", hard: "Difícil", good: "Bom", easy: "Fácil",
      dueToday: "Para revisar hoje",
      emptyDomain: "Nenhum flashcard neste domínio ainda.",
    },
    glossary: { clearSearch: "Limpar busca", termOfDay: "Termo do dia", wrongOnly: "Termos que errei" },
    syllabus: { ofQuestions: "de {total} questões neste banco", studyChapter: "Estudar este capítulo →" },
    onboarding: {
      examCardDesc: "40 questões em 75 minutos, igual à prova real. Revisão de erros no fim.",
      statsQuestions: "1.100 questões",
      badge: "Baseado nos syllabus oficiais do ISTQB",
      heroValueProp: "Tudo que você precisa para passar nas certificações ISTQB, de graça.",
      heroSubtitle: "Preparação gratuita para certificações ISTQB — Foundation e Advanced Level",
      statCerts: "5 certificações ISTQB",
      statLang: "PT/EN",
      statFree: "Gratuito",
      ctaStart: "Escolher certificação →",
      ctaStartFinal: "Escolher minha certificação →",

      featuresTitle: "O que você vai encontrar",
      featureStudyTitle: "Quiz — modo Estudo",
      featureStudyDesc: "Feedback e explicação a cada questão. Filtre por domínio ou revise o que errou.",
      featureExamTitle: "Simulado cronometrado",
      featureSRSTitle: "Revisão espaçada (SM-2)",
      featureSRSDesc: "Modo Revisão no Quiz e Flashcards com Errei/Difícil/Bom/Fácil — repita só o que precisa.",
      featureGlossaryTitle: "Glossário oficial ISTQB",
      featureGlossaryDesc: "Termos oficiais do glossário ISTQB em PT/EN, integrados automaticamente nas explicações.",
      featureProgressTitle: "Progresso detalhado",
      featureProgressDesc: "Cobertura por capítulo, evolução diária, exportar/importar dados.",
      featureBilingualTitle: "100% bilíngue",
      featureBilingualDesc: "Alterne PT/EN a qualquer momento — ideal para quem presta a prova em inglês.",

      mockupTitle: "Veja como funciona",
      mockupDomain: "Fundamentos",
      mockupQuestion: "Qual é a relação correta entre erro, defeito e falha?",
      mockupOptA: "São sinônimos",
      mockupOptB: "Erro gera defeito, que gera falha",
      mockupOptC: "Falha gera erro",
      mockupHint: "Exemplo de questão (CTFL) — clique numa alternativa para ver como funciona:",
      mockupExp: "Um erro (ação humana) introduz um defeito no código, que pode causar uma falha (comportamento incorreto observável) durante a execução.",

      socialFreeText: "100% gratuito, sem cadastro, sem anúncios",
      socialOpenSourceText: "Código aberto no GitHub",
      socialFutureNote: "CTFL e CTAL-TA já disponíveis. Test Manager, AI Testing e Advanced Test Automation chegam em seguida.",

      faqTitle: "Perguntas frequentes",
      faqQ1: "Preciso me cadastrar?",
      faqA1: "Não, nunca. Tudo funciona sem login.",
      faqQ2: "É realmente gratuito?",
      faqA2: "Sim, sem anúncios, sem plano pago, sem pegadinha.",
      faqQ3: "O conteúdo é oficial do ISTQB?",
      faqA3: "Baseado nos syllabus públicos oficiais do ISTQB (CTFL e CTAL-TA hoje, outros a caminho) — o app não é afiliado ao ISTQB.",
      faqQ4: "Funciona no celular?",
      faqA4: "Sim, é instalável como app (PWA), funciona offline.",
      faqQ5: "Posso usar em inglês?",
      faqA5: "Sim, alterne PT/EN a qualquer momento no topo do app.",

      authorTitle: "Sobre o autor",
      authorBio: "Feito por Ironides Francisco — QA Analyst, construído como projeto pessoal de estudo e portfólio.",
    },
    notifications: {
      title: "Lembretes",
      enable: "Ativar notificações",
      enabled: "Notificações ativadas.",
      blocked: "Notificações bloqueadas no navegador. Ative nas configurações do site.",
      dueBody: "Você tem {count} questão(ões) para revisar hoje.",
      staleBody: "Você não estuda há {days} dias. Que tal uma sessão rápida?",
    },
  },
  en: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossary", progress: "Progress" },
    footer: "Independent study material, not affiliated with ISTQB.",
    questionsCount: "questions",
    changeCert: "Change certification",
    langToggleToEn: "Switch language to English", langToggleToPt: "Switch language to Portuguese",
    themeAuto: "Theme: auto", themeLight: "Theme: light", themeDark: "Theme: dark",
    domainAll: "All",
    domainAllDesc: "Mix of all chapters",
    quiz: {
      modeStudy: "Study", modeStudyDesc: "Feedback and explanation for each question",
      modeExam: "Exam Simulation",
      modeExamDesc: "{n} questions · {min} min · review at the end",
      modeSaved: "★ Saved",
      modeSavedDesc: "{n} question(s) marked for review",
      chooseDomain: "Choose the domain",
      allDomains: "All domains",
      wrongBefore: "Mistakes before",
      wrongBeforeDesc: "{n} question(s) you got wrong",
      quantity: "Quantity:", all: "All",
      start: "Start",
      savedReviewHint: "Review the {n} question(s) you marked with ★ during study.",
      examExplain: "Exam Simulation mode replicates the real exam: {n} questions in chapter proportion, {min}-minute timer (extended time for non-native speakers), no feedback until the end.",
      passed: "Passed", failed: "Below the passing score",
      excellentMsg: "Excellent mastery. Ready for the exam.",
      passedMsg: "Passed! Reinforce your weaker domains in the Progress tab.",
      failedMsg: "The passing score is 65% (26/40). Review the mistakes below.",
      backHome: "← Back to start", backShort: "← Back",
      hideReview: "Hide review", showReview: "Review mistakes",
      retakeQuiz: "Retake this quiz",
      reviewErrors: "Mistake review", noErrors: "No mistakes — perfect score!",
      yourAnswer: "Your answer:", notAnswered: "not answered", correctAnswer: "Correct:",
      questionOf: "Question {n} of {total}",
      saved: "★ Saved", saveQuestion: "☆ Save question",
      prev: "← Previous", next: "Next →",
      finishExam: "Finish exam", seeResult: "See result",
      terms: "Terms: ",
      modeSRS: "Review", srsDueDesc: "question(s) due today",
      srsAgain: "Again", srsHard: "Hard", srsGood: "Good", srsEasy: "Easy",
      showGrid: "View all questions", hideGrid: "Hide grid",
      gridSummary: "{answered} of {total} answered · {blank} blank",
      weakestChapter: "Weakest chapter: {chapter} ({pct}%). Study it to improve.",
      studyChapter: "Study {chapter} →",
    },
    stats: {
      importSuccess: "Progress imported successfully.",
      importError: "Invalid file. Use a file exported by this app.",
      answered: "Answered", correct: "Correct", performance: "Performance",
      evolution: "Evolution",
      noHistory: "No history yet. Answer some questions to see your evolution here.",
      emptyWelcome: "You haven't answered any questions yet.",
      emptyCta: "Go to Quiz",
      byDomain: "By domain", noData: "no data",
      coverage: "Coverage by chapter",
      coverageDesc: "Questions seen at least once (Study, Mistakes Only, and Exam Simulation modes)",
      metaTitle: "{cert} goal:",
      metaText: "{examQuestions} questions, minimum {passMark} correct ({passPct}%).",
      exportBtn: "Export progress", importBtn: "Import progress",
      resetBtn: "Reset", resetConfirm: "Reset all progress?",
      precisionLabel: "ACCURACY", coverageLabel: "COVERAGE",
      readinessPrefix: "You're at", readinessSuffix: "readiness for {cert}.",
      readinessLowConfidence: "Keep answering — at least {n} more questions needed for a reliable estimate.",
      pacePrefix: "At this pace, you'll reach 90% in ~", paceSuffix: " weeks.",
      level: "Level", achievementsLabel: "achievements",
      readinessCI: "Real range: {low}%–{high}%",
      readinessCoverage: "Coverage: {pct}% of bank ({seen}/{total})",
      readinessPreliminary: "Preliminary estimate — answer more questions for a reliable verdict.",
      readinessReady: "✓ Ready for the exam",
      readinessNotReady: "Not yet — keep practicing",
      howItWorks: "How does it work?",
      infoAproveitamento: "% correct over all attempts (includes re-answers). Reflects volume, not retention.",
      infoProntidao: "% of unique questions you last got right, with confidence interval. Reflects retention, not volume.",
      streakDesc: "Consecutive days with ≥5 questions answered",
      levelDesc: "Level based on unique correct questions",
    },
    flashcards: {
      flip: "tap to reveal", prev: "← Previous", next: "Next →",
      again: "Again", hard: "Hard", good: "Good", easy: "Easy",
      dueToday: "Due today",
      emptyDomain: "No flashcards in this domain yet.",
    },
    glossary: { clearSearch: "Clear search", termOfDay: "Term of the day", wrongOnly: "Terms I got wrong" },
    syllabus: { ofQuestions: "of {total} questions in this bank", studyChapter: "Study this chapter →" },
    onboarding: {
      examCardDesc: "40 questions in 75 minutes, just like the real exam. Mistake review at the end.",
      statsQuestions: "1,100 questions",
      badge: "Based on official ISTQB syllabi",
      heroValueProp: "Everything you need to pass ISTQB certifications, for free.",
      heroSubtitle: "Free prep for ISTQB certifications — Foundation and Advanced Level",
      statCerts: "5 ISTQB certifications",
      statLang: "PT/EN",
      statFree: "Free",
      ctaStart: "Choose your certification →",
      ctaStartFinal: "Choose my certification →",

      featuresTitle: "What you'll find",
      featureStudyTitle: "Quiz — Study mode",
      featureStudyDesc: "Feedback and explanation for every question. Filter by domain or review your mistakes.",
      featureExamTitle: "Timed exam simulation",
      featureSRSTitle: "Spaced repetition (SM-2)",
      featureSRSDesc: "Review mode in Quiz and Flashcards rating Again/Hard/Good/Easy — repeat only what you need.",
      featureGlossaryTitle: "Official ISTQB glossary",
      featureGlossaryDesc: "Official ISTQB glossary terms in PT/EN, automatically linked in explanations.",
      featureProgressTitle: "Detailed progress",
      featureProgressDesc: "Coverage by chapter, daily evolution, export/import data.",
      featureBilingualTitle: "100% bilingual",
      featureBilingualDesc: "Switch PT/EN anytime — ideal if you're taking the exam in English.",

      mockupTitle: "See how it works",
      mockupDomain: "Fundamentals",
      mockupQuestion: "What is the correct relationship between error, defect, and failure?",
      mockupOptA: "They are synonyms",
      mockupOptB: "Error causes a defect, which causes a failure",
      mockupOptC: "Failure causes an error",
      mockupHint: "Sample question (CTFL) — click an option to see how it works:",
      mockupExp: "An error (human action) introduces a defect into the code, which may cause a failure (observable incorrect behavior) during execution.",

      socialFreeText: "100% free, no sign-up, no ads",
      socialOpenSourceText: "Open source on GitHub",
      socialFutureNote: "CTFL and CTAL-TA are already live. Test Manager, AI Testing, and Advanced Test Automation are coming next.",

      faqTitle: "Frequently asked questions",
      faqQ1: "Do I need to sign up?",
      faqA1: "No, never. Everything works without login.",
      faqQ2: "Is it really free?",
      faqA2: "Yes, no ads, no paid plan, no catch.",
      faqQ3: "Is the content official ISTQB material?",
      faqA3: "Based on official public ISTQB syllabi (CTFL and CTAL-TA today, more on the way) — the app isn't affiliated with ISTQB.",
      faqQ4: "Does it work on mobile?",
      faqA4: "Yes, it's installable as an app (PWA) and works offline.",
      faqQ5: "Can I use it in English?",
      faqA5: "Yes, switch PT/EN anytime at the top of the app.",

      authorTitle: "About the author",
      authorBio: "Built by Ironides Francisco — QA Analyst, made as a personal study and portfolio project.",
    },
    notifications: {
      title: "Reminders",
      enable: "Enable notifications",
      enabled: "Notifications enabled.",
      blocked: "Notifications blocked in browser. Enable it in site settings.",
      dueBody: "You have {count} question(s) to review today.",
      staleBody: "You haven't studied in {days} days. How about a quick session?",
    },
  },
};

export function t(lang, path, vars = {}) {
  const parts = path.split(".");
  let node = UI[lang] || UI.pt;
  for (const p of parts) node = node?.[p];
  if (typeof node !== "string") return path; // fallback visível p/ debug
  return node.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? "");
}
