// Dicionário central de strings de interface (PT/EN).
// Não confundir com conteúdo de questões/flashcards/glossário — esses já são
// bilíngues via locales.pt/locales.en nos próprios dados.
export const UI = {
  pt: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossário", progress: "Progresso" },
    footer: "Material de estudo independente, não afiliado ao ISTQB.",
    questionsCount: "questões",
    domainAll: "Todos",
    domainAllDesc: "Mistura de todos os capítulos",
    quiz: {
      modeStudy: "Estudo", modeStudyDesc: "Feedback e explicação a cada questão",
      modeExam: "Simulado",
      modeExamDesc: "{n} questões · {min} min · revisão no fim",
      modeSaved: "★ Salvos",
      modeSavedDesc: "{n} questão(ões) marcada(s) para revisar",
      chooseDomain: "Escolha o domínio",
      allDomains: "Todos os domínios",
      wrongBefore: "Errei antes",
      wrongBeforeDesc: "{n} questão(ões) que você errou",
      quantity: "Quantidade:", all: "Todas",
      start: "Iniciar",
      savedReviewHint: "Revise as {n} questão(ões) que você marcou com ★ durante o estudo.",
      examExplain: "O modo Simulado reproduz a prova: {n} questões na proporção dos capítulos, cronômetro de {min} minutos (tempo estendido para não-nativos), sem feedback até o final.",
      passed: "Aprovado", failed: "Abaixo da nota de corte",
      excellentMsg: "Excelente domínio. Pronto para a prova.",
      passedMsg: "Passou! Reforce os domínios mais fracos na aba Progresso.",
      failedMsg: "A nota de corte é 65% (26/40). Revise os erros abaixo.",
      backHome: "← Voltar ao início", backShort: "← Voltar",
      hideReview: "Ocultar revisão", showReview: "Revisar erros",
      retakeQuiz: "Refazer este quiz",
      reviewErrors: "Revisão dos erros", noErrors: "Nenhum erro — gabaritou!",
      yourAnswer: "Sua resposta:", notAnswered: "não respondida", correctAnswer: "Correta:",
      questionOf: "Questão {n} de {total}",
      saved: "★ Salvo", saveQuestion: "☆ Salvar questão",
      prev: "← Anterior", next: "Próxima →",
      finishExam: "Finalizar simulado", seeResult: "Ver resultado",
      terms: "Termos: ",
    },
    stats: {
      importSuccess: "Progresso importado com sucesso.",
      importError: "Arquivo inválido. Use um arquivo exportado por este app.",
      answered: "Respondidas", correct: "Acertos", performance: "Aproveitamento",
      evolution: "Evolução",
      noHistory: "Sem histórico ainda. Responda algumas questões para ver sua evolução aqui.",
      byDomain: "Por domínio", noData: "sem dados",
      coverage: "Cobertura por capítulo",
      coverageDesc: "Questões vistas ao menos uma vez (modos Estudo e Errei antes)",
      metaTitle: "Meta CTFL v4.0:",
      metaText: "40 questões, mínimo 26 acertos (65%). Os capítulos 4 (Técnicas) e 5 (Gerenciamento) somam metade do exame — priorize-os. Há cerca de 8 questões K3 (aplicação), as mais difíceis.",
      exportBtn: "Exportar progresso", importBtn: "Importar progresso",
      resetBtn: "Zerar", resetConfirm: "Zerar todo o progresso?",
    },
    flashcards: { flip: "toque para revelar", prev: "← Anterior", next: "Próximo →" },
    syllabus: { ofQuestions: "de {total} questões neste banco", studyChapter: "Estudar este capítulo →" },
    onboarding: {
      examCardDesc: "40 questões em 75 minutos, igual à prova real. Revisão de erros no fim.",
      statsQuestions: "200 questões",
    },
  },
  en: {
    tabs: { quiz: "Quiz", syllabus: "Syllabus", flashcards: "Flashcards", glossary: "Glossary", progress: "Progress" },
    footer: "Independent study material, not affiliated with ISTQB.",
    questionsCount: "questions",
    domainAll: "All",
    domainAllDesc: "Mix of all chapters",
    quiz: {
      modeStudy: "Study", modeStudyDesc: "Feedback and explanation for each question",
      modeExam: "Exam Simulation",
      modeExamDesc: "{n} questions · {min} min · review at the end",
      modeSaved: "★ Saved",
      modeSavedDesc: "{n} question(s) marked for review",
      chooseDomain: "Choose the domain",
      allDomains: "All domains",
      wrongBefore: "Mistakes before",
      wrongBeforeDesc: "{n} question(s) you got wrong",
      quantity: "Quantity:", all: "All",
      start: "Start",
      savedReviewHint: "Review the {n} question(s) you marked with ★ during study.",
      examExplain: "Exam Simulation mode replicates the real exam: {n} questions in chapter proportion, {min}-minute timer (extended time for non-native speakers), no feedback until the end.",
      passed: "Passed", failed: "Below the passing score",
      excellentMsg: "Excellent mastery. Ready for the exam.",
      passedMsg: "Passed! Reinforce your weaker domains in the Progress tab.",
      failedMsg: "The passing score is 65% (26/40). Review the mistakes below.",
      backHome: "← Back to start", backShort: "← Back",
      hideReview: "Hide review", showReview: "Review mistakes",
      retakeQuiz: "Retake this quiz",
      reviewErrors: "Mistake review", noErrors: "No mistakes — perfect score!",
      yourAnswer: "Your answer:", notAnswered: "not answered", correctAnswer: "Correct:",
      questionOf: "Question {n} of {total}",
      saved: "★ Saved", saveQuestion: "☆ Save question",
      prev: "← Previous", next: "Next →",
      finishExam: "Finish exam", seeResult: "See result",
      terms: "Terms: ",
    },
    stats: {
      importSuccess: "Progress imported successfully.",
      importError: "Invalid file. Use a file exported by this app.",
      answered: "Answered", correct: "Correct", performance: "Performance",
      evolution: "Evolution",
      noHistory: "No history yet. Answer some questions to see your evolution here.",
      byDomain: "By domain", noData: "no data",
      coverage: "Coverage by chapter",
      coverageDesc: "Questions seen at least once (Study and Mistakes Only modes)",
      metaTitle: "CTFL v4.0 goal:",
      metaText: "40 questions, minimum 26 correct (65%). Chapters 4 (Techniques) and 5 (Management) make up half the exam — prioritize them. There are about 8 K3 (application) questions, the hardest ones.",
      exportBtn: "Export progress", importBtn: "Import progress",
      resetBtn: "Reset", resetConfirm: "Reset all progress?",
    },
    flashcards: { flip: "tap to reveal", prev: "← Previous", next: "Next →" },
    syllabus: { ofQuestions: "of {total} questions in this bank", studyChapter: "Study this chapter →" },
    onboarding: {
      examCardDesc: "40 questions in 75 minutes, just like the real exam. Mistake review at the end.",
      statsQuestions: "200 questions",
    },
  },
};

export function t(lang, path, vars = {}) {
  const parts = path.split(".");
  let node = UI[lang] || UI.pt;
  for (const p of parts) node = node?.[p];
  if (typeof node !== "string") return path; // fallback visível p/ debug
  return node.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? "");
}
